### ISSUE TITLE
Camera issue when affecting players

### ISSUE THREAD

**Issue by Napasinitro** [min2222/Entity-Tickrate-API#5]
It's a weird visual issue that is quite disorientating. When lowering or increasing tickrate past 20 it's almost as though FPS goes down as the game becomes incredibly choppy even at 19 ticks or 21. Now I have checked and for a fact, it's not a FPS issue for sure. I tried with just the mod

**Comment by Napasinitro** [comment]
it was version 1.20.1 forge btw.

**Comment by min2222** [comment]
do you have video or smth?

**Comment by Napasinitro** [comment]
https://imgur.com/a/RFDZFlY

sorry for the mega late response

**Comment by Napasinitro** [comment]
question why has this been marked as complete the error persists

**Comment by min2222** [comment]
it's fixed, try with latest ver

**Comment by Napasinitro** [comment]
Thank you good sir so much I hadn't seen the update. Just tested tried it works so well thank you so much!
