### ISSUE TITLE
Problem affecting other players

### ISSUE THREAD

**Issue by Wesleyx12** [min2222/Entity-Tickrate-API#8]
Changing a player’s tick rate causes the game to freeze, no matter the adjustment. Running on version 1.20.

The visuals get super choppy, almost like an FPS drop, but it’s definitely not that. Happens even with tiny changes like 17 or 26 ticks. Tested on Forge 1.20.1 with just the mod, same issue.

https://github.com/user-attachments/assets/151a285a-6ba1-4abd-8f4f-15b8305ce642

**Comment by min2222** [comment]
please use latest version of mod, the issue of video you presented is already fixed

**Comment by Wesleyx12** [comment]
thank you very much !
